// Lista de Nombres de sensores
const sensorNames = [
  //COSMITET
  'COCLOCOSMIAP02', 'COCLOCOSMIAP05', 'COCLOCOSMIAP06', 'COCLOCOSMIAP07',
  'COCLOCOSMIAST03', 'COCLOCOSMIAST04',
  'COCLOCOSMIBD01', 'COCLOCOSMIBD02', 'COCLOCOSMIBD03', 'COCLOCOSMIBD04',
  'COCLOCOSMIBK01', 'COCLOCOSMIDES01', 'COCLOCOSMIFI01', 'COCLOCOSMIREP02', 'COCLOCOSMIREP03', 'COCLOCOSMISTG01',

  //DUARTE
  'COCLOCDUARAP01', 'COCLOCDUARAST01', 'COCLOCDUAREP02', 'COCLOCDUARFI01', 'COCLOCDUARST02',
  'COCLOCDUARTBD01', 'COCLOCDUARTBD02', 'COCLOCDUARTBK01', 'COCLOCDUARTSTG01',

  //DUANA
  'COCLODUANAAP01', 'COCLODUANADB05', 'COCLODUANADU01', 'COCLODUANAP02', 'COCLODUANAP03',

  //COSMITET
  'COCLOESECAP02', 'COCLOESECAP03', 'COCLOESECAP04', 'COCLOESECAP05', 'COCLOESECAP06', 'COCLOESECAP07', 'COCLOESECAP08', 'COCLOESECAP09',
  'COCLOESECAP10', 'COCLOESECAP11', 'COCLOESECAP12', 'COCLOESECAP13', 'COCLOESECAP14', 'COCLOESECAP15', 'COCLOESECAP16', 'COCLOESECAP17',
  'COCLOESECAP18', 'COCLOESECAP19', 'COCLOESECAP20', 'COCLOESECAP21', 'COCLOESECAP22', 'COCLOESECAP23', 'COCLOESECAP24', 'COCLOESECDA01',

  //PEÑITAS
  'COCLOPENIAP01', 'COCLOPENIAP02', 'COCLOPENIAP03', 'COCLOPENIAP04', 'COCLOPENIAST02', 'COCLOPENIBD02', 'COCLOPENIBD03', 'COCLOPENIBK01',
  'COCLOPENIFI01', 'COCLOPENIREP01', 'COCLOPENISTG01',

  //ROCHE
  'COCLOROCHEAP01',

  //SSOFIA
  'COCLOSSFIAAP01', 'COCLOSSFIABD01', 'COCLOSSFIABD02', 'COCLOSSFIABD03', 'COCLOSSFIABK01', 'COCLOSSFIADES01', 'COCLOSSFIAREP01',
  'COCLOSSFIAST02', 'COCLOSSFIASTG01', 'COCLOSSOFIAAP02',

  //CAMARACC


  // Añade más nombres según sea necesario
];

// Lista de Nombres de sensores específicos para 192.168.200.160
const sensorNamesAlt = [
  'COCLOCCCDEV00', 'COCLOCCCDEVL02', 'COCLOCCCDEVL35', 'COCLOCCCDEVL98', 'COCLOCCCDEVW36', 'COCLOCCCPRDB01', 'COCLOCCCPRDB02',
  'COCLOCCCPRDB03', 'COCLOCCCPRDB06', 'COCLOCCCPRDL01', 'COCLOCCCPRDL02', 'COCLOCCCPRDL03', 'COCLOCCCPRDL06', 'COCLOCCCPRDL07',
  'COCLOCCCPRDL08', 'COCLOCCCPRDL09', 'COCLOCCCPRDL10', 'COCLOCCCPRDL15', 'COCLOCCCPRDL16', 'COCLOCCCPRDL17', 'COCLOCCCPRDL18',
  'COCLOCCCPRDL37', 'COCLOCCCPRDL41', 'COCLOCCCPRDL48', 'COCLOCCCPRDL49', 'COCLOCCCPRDW10', 'COCLOCCCPRDW22', 'COCLOCCCPRDW23',
  'COCLOCCCPRDW24', 'COCLOCCCPRDW25', 'COCLOCCCPRDW30', 'COCLOCCCPRDW35', 'COCLOCCCPRDW48', 'COCLOCCCPRDW97', 'COCLOCCCPRDW98',
  'COCLOCCCTST00', 'COCLOCCCTST01', 'COCLOCCCTST02', 'COCLOCCCTST03', 'COCLOCCCTST06', 'COCLOCCCTST07', 'COCLOCCCTST09', 'COCLOCCCTST10',
  'COCLOCCCTST11', 'COCLOCCCTST15', 'COCLOCCCTSTL01', 'COCLOCCCTSTL02', 'COCLOCCCTSTL03', 'COCLOCCCTSTL06', 'COCLOCCCTSTL07', 'COCLOCCCTSTL09',
  'COCLOCCCTSTL10', 'COCLOCCCTSTL15', 'COCLOCCCTSTL41', 'COCLOCCCDES48', 'COCLOCERTORI01', 'COCLOCERTORI02', 'COCLOSERTORIBD01'
];

// Exportar ambas listas como un objeto
module.exports = {
  sensorNames,
  sensorNamesAlt
};